### ISSUE TITLE
auth in firebases

### ISSUE THREAD

**Issue by Dida27** [idraksheikh/School-Management-System#12]
how i can know the registration id and the password?can u tell me?

**Comment by idraksheikh** [comment]
Hi @Dida27 ,
There are role base authentication in the application. we can do login for different Teacher and students.
1. For **Teacher** : Registration Id="TA202300001" Password= "12345"
2. For **Student** : Registration Id="ST202301001" Password= "12345"

We are still working on this app. We are also including the admin functionality for registration of students and teachers. Your suggestion and contribution is appreciated.
